name: Bug Report
description: Report a bug or unexpected behavior in pyPFC
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: pypfc-version
    attributes:
      label: pyPFC Version
      description: What version of pyPFC are you using?
      placeholder: "Use `pip show pypfc` to find the version"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "Use `python --version`"
    validations:
      required: true

  - type: input
    id: pytorch-version
    attributes:
      label: PyTorch Version
      description: What version of PyTorch are you using?
      placeholder: "Use `torch.__version__`"
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: Are you using CPU or GPU?
      options:
        - CPU only
        - GPU (CUDA)
        - Not sure
    validations:
      required: true

  - type: input
    id: gpu-info
    attributes:
      label: GPU Information (if applicable)
      description: GPU model and CUDA version
      placeholder: "e.g., NVIDIA RTX 4090, CUDA 12.1"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what went wrong..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import pyPFC
        2. Set up simulation with parameters...
        3. Run simulation...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe the expected outcome..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened, including any error messages
      placeholder: "Include full error messages and stack traces..."
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        import pypfc
        # Your minimal reproduction code here
      render: python
    validations:
      required: true

  - type: textarea
    id: simulation-params
    attributes:
      label: Simulation Parameters
      description: Grid size, domain dimensions, and other relevant parameters
      placeholder: |
        - Grid size: nx=64, ny=64, nz=64
        - Domain size: [10.0, 10.0, 10.0]
        - Time step: 0.01
        - Other parameters...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other relevant information..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a minimal code example that reproduces the issue
          required: true
        - label: I have included all relevant system information
          required: true