name: Feature Request
description: Suggest a new feature or enhancement for pyPFC
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: "Describe the feature you want..."
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of pyPFC would this feature affect?
      options:
        - Core simulation engine
        - GPU/CUDA acceleration
        - I/O operations (VTK, XYZ)
        - Crystal structure analysis
        - Performance optimization
        - Documentation
        - Examples/tutorials
        - API design
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the workflow it would improve
      placeholder: "Why would this feature be useful? What problem does it solve?"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: "How should this feature work? What should the API look like?"

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: "Technical suggestions, algorithms, or approaches..."

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Show how this feature would be used in code
      placeholder: |
        # Example of how the feature might be used
        import pypfc
        sim = pypfc.Simulation()
        # New feature usage here...
      render: python

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your work?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my research
        - Urgent - Blocking my current work

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: "What alternatives have you tried or considered?"

  - type: textarea
    id: related-features
    attributes:
      label: Related Features
      description: Are there any existing features this would build upon or interact with?
      placeholder: "How does this relate to current pyPFC functionality?"

  - type: checkboxes
    id: feature-scope
    attributes:
      label: Feature Scope
      description: What aspects should this feature include?
      options:
        - label: New API methods/functions
        - label: Performance improvements
        - label: Documentation updates
        - label: Example code/tutorials
        - label: Unit tests
        - label: Backward compatibility considerations

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Links to papers, similar implementations, or other context..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I understand this is a volunteer-driven open source project
          required: true