name: Performance Issue
description: Report performance problems, memory issues, or optimization opportunities
title: "[PERFORMANCE] "
labels: ["performance"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a performance issue! Performance data helps us optimize pyPFC for better user experience.

  - type: input
    id: pypfc-version
    attributes:
      label: pyPFC Version
      description: What version of pyPFC are you using?
      placeholder: "Use `pip show pypfc` to find the version"
    validations:
      required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: Performance Issue Type
      description: What kind of performance issue are you experiencing?
      options:
        - Slow execution time
        - High memory usage
        - GPU memory overflow
        - CPU/GPU utilization issues
        - Scaling problems (large simulations)
        - Memory leaks
        - Inefficient algorithms
        - Other
    validations:
      required: true

  - type: textarea
    id: hardware-specs
    attributes:
      label: Hardware Specifications
      description: Detailed information about your hardware
      placeholder: |
        CPU: (e.g., Intel i9-12900K, AMD Ryzen 9 5900X)
        RAM: (e.g., 32GB DDR4)
        GPU: (e.g., NVIDIA RTX 4090 24GB)
        Storage: (e.g., NVMe SSD)
        OS: (e.g., Ubuntu 22.04, Windows 11)
    validations:
      required: true

  - type: textarea
    id: simulation-parameters
    attributes:
      label: Simulation Parameters
      description: Grid size, domain dimensions, and simulation settings
      placeholder: |
        Grid size: nx=?, ny=?, nz=?
        Domain size: [?, ?, ?]
        Time steps: ?
        Update scheme: ?
        Precision: float32/float64
        Device: CPU/GPU
    validations:
      required: true

  - type: textarea
    id: performance-data
    attributes:
      label: Performance Measurements
      description: Actual performance data (timing, memory usage, etc.)
      placeholder: |
        Execution time: ? seconds
        Memory usage: ? GB
        GPU memory: ? GB
        CPU utilization: ?%
        GPU utilization: ?%
        
        Include any profiling data if available.
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance were you expecting?
      placeholder: |
        Expected execution time: ? seconds
        Expected memory usage: ? GB
        Basis for expectation (scaling estimates, similar simulations, etc.)

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Minimal code that demonstrates the performance issue
      placeholder: |
        import pypfc
        import time
        
        # Setup simulation
        sim = pypfc.Simulation()
        # ... configuration ...
        
        # Performance measurement
        start_time = time.time()
        # ... slow operation ...
        end_time = time.time()
        print(f"Execution time: {end_time - start_time:.2f} seconds")
      render: python
    validations:
      required: true

  - type: dropdown
    id: data-precision
    attributes:
      label: Data Precision
      description: What precision are you using?
      options:
        - Single precision (float32)
        - Double precision (float64)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: device-usage
    attributes:
      label: Device Usage
      description: Are you using CPU or GPU?
      options:
        - CPU
        - GPU
    validations:
      required: true

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data (Optional)
      description: Any profiling information (cProfile, NVIDIA Nsight, etc.)
      placeholder: "Paste profiling output or attach profiling files..."

  - type: textarea
    id: comparison-data
    attributes:
      label: Comparison Data (Optional)
      description: Performance comparison with other tools or versions
      placeholder: |
        Comparison with:
        - Previous pyPFC versions
        - Other simulation software
        - Theoretical expectations

  - type: textarea
    id: optimization-attempts
    attributes:
      label: Optimization Attempts
      description: What have you tried to improve performance?
      placeholder: |
        - Changed grid size
        - Adjusted precision
        - Modified parameters
        - Used different device
        - Other approaches...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "Environment details, constraints, specific requirements..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have provided detailed hardware specifications
          required: true
        - label: I have included actual performance measurements
          required: true
        - label: I have provided a reproducible code example
          required: true
        - label: I have searched for similar performance issues
          required: true